name: codacy-coverage-reporter

on: ["push"]

jobs:
  codacy-coverage-reporter:
    runs-on: macos-latest
    name: codacy-coverage-reporter
    steps:
      - name: install coverage report
        run: gem install slather
      - name: coverage report
        run: slather coverage -x --output-directory ./screenshots --scheme lab3 lab3.xcodeproj
          
      - name: upload coverage report
        run: export CODACY_PROJECT_TOKEN=2f6e47e11c0c4937a9dc038a6b829320
